# Generated by Django 5.2.9 on 2026-02-21 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_school_created_by'),
        ('users', '0008_parentprofile_children'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_items', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discount_type', models.CharField(choices=[('sibling', 'Sibling'), ('general', 'General'), ('scholarship', 'Scholarship')], max_length=20)),
                ('value_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('fee_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='finance.feeitem')),
            ],
        ),
        migrations.CreateModel(
            name='GradeFeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(choices=[('per_term', 'Per Term'), ('yearly', 'Yearly'), ('once_time', 'One Time')])),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_fee_items', to='core.academicyear')),
                ('fee_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='finance.feeitem')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_fee_items', to='core.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.academicyear')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='users.studentprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.term')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_discounts', to='core.academicyear')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_discounts', to='finance.discount')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='users.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_assignments', to='core.academicyear')),
                ('grade_fee_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigments', to='finance.gradefeeitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_assignments', to='users.studentprofile')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_assignments', to='core.term')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='finance.payment')),
                ('fee_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_items', to='finance.studentfeeassignment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='gradefeeitem',
            constraint=models.UniqueConstraint(fields=('academic_year', 'fee_item', 'grade'), name='unique_grade_fee_item'),
        ),
        migrations.AddConstraint(
            model_name='studentdiscount',
            constraint=models.UniqueConstraint(fields=('student', 'discount', 'academic_year'), name='unique_student_discount'),
        ),
        migrations.AddConstraint(
            model_name='studentfeeassignment',
            constraint=models.UniqueConstraint(fields=('student', 'grade_fee_item', 'term'), name='unique_student_fee_assignment'),
        ),
    ]
