# Generated by Django 5.2.9 on 2026-03-01 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('finance', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.term'),
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='studentdiscount',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_discounts', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='studentdiscount',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentdiscount',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_discounts', to='finance.discount'),
        ),
        migrations.AddField(
            model_name='studentdiscount',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='studentfeeassignment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_assignments', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='studentfeeassignment',
            name='grade_fee_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigments', to='finance.gradefeeitem'),
        ),
        migrations.AddField(
            model_name='studentfeeassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_assignments', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='studentfeeassignment',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_assignments', to='core.term'),
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='fee_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_items', to='finance.studentfeeassignment'),
        ),
        migrations.AddConstraint(
            model_name='gradefeeitem',
            constraint=models.UniqueConstraint(fields=('academic_year', 'fee_item', 'grade'), name='unique_grade_fee_item'),
        ),
        migrations.AddConstraint(
            model_name='studentdiscount',
            constraint=models.UniqueConstraint(fields=('student', 'discount', 'academic_year'), name='unique_student_discount'),
        ),
        migrations.AddConstraint(
            model_name='studentfeeassignment',
            constraint=models.UniqueConstraint(fields=('student', 'grade_fee_item', 'term'), name='unique_student_fee_assignment'),
        ),
    ]
