# Generated by Django 5.2.9 on 2026-02-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradefeeitem',
            name='frequency',
            field=models.CharField(choices=[('per_term', 'Per Term'), ('yearly', 'Yearly'), ('one_time', 'One Time')]),
        ),
    ]
