# Generated by Django 5.2.9 on 2026-03-01 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment_items', to='core.school'),
            preserve_default=False,
        ),
    ]
