# Generated by Django 5.2.9 on 2026-04-06 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('finance', '0003_payment_school_paymentitem_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradefeeitem',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grade_fee_item', to='core.term'),
        ),
    ]
