# Generated by Django 5.2.9 on 2026-02-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_studentdiscount_assigned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
