# Generated by Django 5.2.9 on 2026-04-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('finance', '0004_gradefeeitem_term'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gradefeeitem',
            name='unique_grade_fee_item',
        ),
        migrations.AddConstraint(
            model_name='gradefeeitem',
            constraint=models.UniqueConstraint(condition=models.Q(('term__isnull', False)), fields=('academic_year', 'fee_item', 'grade', 'term'), name='unique_grade_fee_item_with_term'),
        ),
        migrations.AddConstraint(
            model_name='gradefeeitem',
            constraint=models.UniqueConstraint(condition=models.Q(('term__isnull', True)), fields=('academic_year', 'fee_item', 'grade'), name='unique_grade_fee_item_when_term_is_null'),
        ),
    ]
