# Generated by Django 5.2.9 on 2025-12-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(null=True, related_name='users', to='users.role'),
        ),
    ]
