# Generated by Django 5.2.9 on 2026-03-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_role',
            field=models.CharField(blank=True, choices=[('studentprofile', 'student'), ('teacherprofile', 'teacher'), ('adminprofile', 'admin'), ('staffprofile', 'staff')], max_length=20, null=True),
        ),
    ]
