# Generated by Django 5.2.9 on 2026-03-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_customuser_active_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='active_role',
            field=models.CharField(blank=True, choices=[('studentprofile', 'student'), ('teacherprofile', 'teacher'), ('adminprofile', 'admin'), ('staffprofile', 'staff'), ('parentprofile', 'parent')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('phone_number', 'email'), name='unique_phone_and_email_when_email_not_null'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', True)), fields=('phone_number',), name='unique_phone_when_email_null'),
        ),
    ]
