# Generated by Django 5.2.9 on 2025-12-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role_customuser_school_role_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='role',
            new_name='roles',
        ),
    ]
