# Generated by Django 5.2.9 on 2025-12-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0003_rename_role_customuser_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='school',
        ),
        migrations.AddField(
            model_name='customuser',
            name='school',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.school'),
        ),
    ]
