# Generated by Django 5.2.9 on 2026-02-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='assesment_number',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='assessment_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
