# Generated by Django 5.2.9 on 2026-02-18 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_school_map_location'),
        ('users', '0004_remove_studentprofile_assesment_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='schools',
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='parents', to='core.school'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='staff', to='core.school'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='enrollment_status',
            field=models.CharField(choices=[('applied', 'Applied'), ('enrolled', 'Enrolled'), ('transferred', 'Transferred'), ('graduated', 'Graduated'), ('expelled', 'Expelled'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='core.school'),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='adminprofile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('schools', models.ManyToManyField(blank=True, related_name='admins', to='core.school')),
            ],
        ),
    ]
