# Generated by Django 5.2.9 on 2025-12-15 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_school_customuser_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='school',
            new_name='schools',
        ),
    ]
