# Generated by Django 5.2.9 on 2026-03-13 05:50

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_studentprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[utils.validators.validate_not_in_the_future]),
        ),
    ]
