# Generated by Django 5.2.9 on 2025-12-15 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_school_role_schools'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='school',
            new_name='schools',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='schools',
            new_name='school',
        ),
    ]
