# Generated by Django 5.2.9 on 2026-02-18 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_school_map_location'),
        ('users', '0006_studentprofile_created_at_studentprofile_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='core.grade'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream', to='core.stream'),
        ),
    ]
