# Generated by Django 5.2.9 on 2026-02-19 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_studentprofile_enrollment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to=settings.AUTH_USER_MODEL),
        ),
    ]
