# Generated by Django 5.2.9 on 2026-02-24 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_term_options_remove_term_sequence_term_order'),
        ('users', '0008_parentprofile_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.grade'),
        ),
    ]
