# Generated by Django 5.2.9 on 2025-12-15 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade_representatives',
            field=models.ManyToManyField(blank=True, help_text='parents representing classes', related_name='grades_representing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_teachers',
            field=models.ManyToManyField(blank=True, related_name='grades_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='map_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='core.maplocation'),
        ),
        migrations.AddField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.school'),
        ),
        migrations.AddField(
            model_name='stream',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='core.school'),
        ),
        migrations.AddField(
            model_name='grade',
            name='streams',
            field=models.ManyToManyField(related_name='grades', to='core.stream'),
        ),
        migrations.AddField(
            model_name='streamteacher',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_teachers', to='core.grade'),
        ),
        migrations.AddField(
            model_name='streamteacher',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_teachers', to='core.stream'),
        ),
        migrations.AddField(
            model_name='streamteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_stream_per_school'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_grade_per_school'),
        ),
        migrations.AddConstraint(
            model_name='streamteacher',
            constraint=models.UniqueConstraint(fields=('grade', 'stream', 'teacher'), name='unique_stream_teacher_assignement'),
        ),
    ]
