# Generated by Django 5.2.9 on 2025-12-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='streams',
            field=models.ManyToManyField(blank=True, related_name='grades', to='core.stream'),
        ),
    ]
