# Generated by Django 5.2.9 on 2025-12-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_grade_description_alter_grade_streams'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-15 13:43:30.254324'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stream',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
