# Generated by Django 5.2.9 on 2026-02-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_school_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='term',
            name='sequence',
        ),
        migrations.AddField(
            model_name='term',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
