# Generated by Django 5.2.9 on 2026-02-24 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_term_options_remove_term_sequence_term_order'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='term',
            name='unique_term_name_per_year',
        ),
        migrations.AddField(
            model_name='term',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='core.school'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'name'), name='unique_term_name_per_year'),
        ),
    ]
