# Generated by Django 5.2.9 on 2025-12-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_academicyear_term_and_more'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='academicyear',
            name='unique_academic_year_per_school',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_academic_year_per_school', violation_error_code=409, violation_error_message='An academic year with the same name exists'),
        ),
    ]
